create table Book (
    id int generated by default as identity primary key,
    name varchar not null,
    year int check ( year >= 1 ),
    author varchar not null
);

create table Person (
    id int generated by default as identity primary key,
    name varchar not null,
    surname varchar not null,
    age int check ( age >= 1 ),
    email varchar unique not null
);

create table Booking (
    id int generated by default as identity primary key,
    person_id int not null,
    book_id int not null,
    foreign key (person_id) references Person (id),
    foreign key (book_id) references Book (id),
    start_time_of_booking date not null,
    finish_time_of_booking date,
    is_finished boolean not null
)